# Generated by Django 3.2 on 2022-08-09 04:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_categories', models.CharField(max_length=100, verbose_name='category')),
                ('company_sub_categories', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('categories_image', models.ImageField(blank=True, upload_to='category')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('established_date', models.DateField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.PositiveIntegerField(max_length=7)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 14 digits allowed.', regex='^\\+?1?\\d{9,10}$')])),
                ('website', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('about_company', models.TextField(max_length=2000)),
                ('Facebook', models.URLField(blank=True)),
                ('Twitter', models.URLField(blank=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('Instagram', models.URLField(blank=True)),
                ('Youtube', models.URLField(blank=True)),
                ('Others', models.URLField(blank=True)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='companyimage')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Address.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.companycategories', verbose_name='company category')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Address.state')),
            ],
        ),
        migrations.CreateModel(
            name='HrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(max_length=30)),
                ('hr_phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 11 digits allowed.', regex='^\\+?1?\\d{9,10}$')])),
                ('hr_email', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer', verbose_name='employer')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrolemodal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField(max_length=13)),
                ('User_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.rolemodel', verbose_name='Company_infos')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=355, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 14 digits allowed.', regex='^\\+?1?\\d{9,10}$')])),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('pin_code', models.PositiveIntegerField(blank=True, max_length=7, null=True)),
                ('looking_for', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full Time', max_length=30, null=True)),
                ('workig_experiance', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('about_me', models.TextField(blank=True, max_length=2000, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.country')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companycategories', verbose_name='job catogory')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_designation', models.CharField(max_length=100, verbose_name='job designation')),
                ('pin_code', models.PositiveIntegerField(max_length=7)),
                ('description', models.TextField(blank=True)),
                ('about_company', models.TextField(blank=True)),
                ('job_opening_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('Number_vacancy', models.CharField(max_length=10, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('salary_min', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('salary_max', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('company_profile_image', models.ImageField(blank=True, null=True, upload_to='companyimage')),
                ('job_end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Address.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.country')),
                ('employer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='job_catagories', chained_model_field='industry', on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
                ('hr_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='employer', chained_model_field='employer', on_delete=django.db.models.deletion.CASCADE, to='jobs.hrinfo')),
                ('job_catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.companycategories', verbose_name='job category')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='staff name')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Address.state')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('job_Application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('selection_status', models.CharField(choices=[('Pending', 'Pending'), ('HR round pending', 'HR round pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Candidate joined', 'Candidate joined')], max_length=30)),
                ('employer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='job_catagories', chained_model_field='industry', on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
                ('hr_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='employer', chained_model_field='employer', on_delete=django.db.models.deletion.CASCADE, to='jobs.hrinfo')),
                ('job_Application_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hr_name', chained_model_field='hr_name', on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('job_catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.companycategories', verbose_name='job category')),
                ('jobseeker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='staff name')),
            ],
        ),
    ]
