# Generated by Django 3.2 on 2022-08-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_company_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='companyimage'),
        ),
    ]
