# Generated by Django 3.2 on 2022-08-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_employer_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='companyimage'),
        ),
    ]
