# Generated by Django 3.2 on 2022-08-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_employer_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycategories',
            name='categories_image',
        ),
    ]
