# Generated by Django 3.2 on 2022-08-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_companycategories_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategories',
            name='categories_image',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
    ]
