# Generated by Django 3.2 on 2022-08-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_companycategories_categories_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='id',
            new_name='job_seeker_id',
        ),
    ]
