# Generated by Django 3.2 on 2022-08-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_id_jobseeker_job_seeker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_phone_verified',
        ),
    ]
