# Generated by Django 3.2 on 2022-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobseeker_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
