# Generated by Django 3.2 on 2022-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobseeker_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
