# Generated by Django 3.2 on 2022-08-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20220822_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
