# Generated by Django 3.2 on 2022-08-24 12:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('jobs', '0012_alter_jobseeker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.city'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.country'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companycategories', verbose_name='company category'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.state'),
        ),
    ]
