# Generated by Django 3.2 on 2022-08-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_rename_company_image_employer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=55)),
                ('job_description', models.TextField(max_length=1055)),
                ('comapny_Name', models.CharField(max_length=55)),
                ('offered_salary', models.CharField(max_length=55)),
                ('experience', models.CharField(max_length=55)),
                ('qualification', models.CharField(max_length=55)),
                ('deadline_date', models.DateField()),
                ('States', models.CharField(max_length=55)),
                ('complete_address', models.CharField(max_length=155)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
