# Generated by Django 3.2 on 2022-08-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='States',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='comapny_Name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='complete_address',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_description',
            field=models.TextField(blank=True, max_length=1055, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='offered_salary',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='qualification',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
