# Generated by Django 3.2 on 2022-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20220826_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
