# Generated by Django 3.2 on 2022-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20220826_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_image2',
            field=models.ImageField(blank=True, null=True, upload_to='companyimage'),
        ),
    ]
