# Generated by Django 3.2 on 2022-08-26 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobposting_company_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 14 digits allowed.', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
