# Generated by Django 3.2 on 2022-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobposting_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='verify the employer then save'),
        ),
    ]
