# Generated by Django 3.2 on 2022-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20220902_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage'),
        ),
    ]
