# Generated by Django 3.2 on 2022-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_jobseeker_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(default='default/1.png', upload_to='profileimage'),
        ),
    ]
