# Generated by Django 3.2 on 2022-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_jobseeker_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='workig_experiance',
            new_name='working_experience',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(default='default/2.jpg', upload_to='profileimage'),
        ),
    ]
