# Generated by Django 3.2 on 2022-09-15 07:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20220912_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='job_category',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='job_category',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.CompanyCategories'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
