# Generated by Django 3.2 on 2022-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20220915_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.CharField(choices=[('10th ', '10th'), ('12th', '12th'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
