# Generated by Django 3.2 on 2022-09-16 09:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_alter_jobseeker_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='employer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='job_catagories', chained_model_field='industry', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='hr_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='employer', chained_model_field='employer', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.hrinfo'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_Application_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='hr_name', chained_model_field='hr_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
