# Generated by Django 3.2 on 2022-09-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0028_auto_20220916_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='staff name'),
        ),
    ]
