# Generated by Django 3.2 on 2022-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_jobseeker_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategories',
            name='company_categories',
            field=models.CharField(max_length=100, unique=True, verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('job_catagories', 'jobseeker_name', 'job_Application_name')},
        ),
    ]
