# Generated by Django 3.2 on 2022-10-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_auto_20220926_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='companycategories',
            options={'verbose_name_plural': 'Company Categories'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Employer'},
        ),
        migrations.AlterModelOptions(
            name='hrinfo',
            options={'verbose_name_plural': 'Hr'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job List'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'verbose_name_plural': 'Post Job'},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'verbose_name_plural': 'Job seeker'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': 'Job Type'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'User role'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='Facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Others',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
