# Generated by Django 3.2 on 2022-10-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20221011_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, max_length=7, null=True),
        ),
    ]
