# Generated by Django 3.2 on 2022-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_alter_employer_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, max_length=7, null=True),
        ),
    ]
