# Generated by Django 3.2 on 2022-10-11 06:55

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_alter_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hr_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='employer', chained_model_field='employer', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.hrinfo'),
        ),
    ]
