# Generated by Django 3.2 on 2022-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_alter_job_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_by',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='published_by',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=30, null=True),
        ),
    ]
