# Generated by Django 3.2 on 2022-10-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20221011_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='offered_salary',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='published_by',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], default='Frontend', max_length=30, null=True),
        ),
    ]
