# Generated by Django 3.2 on 2022-10-12 09:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20221012_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='about_company',
            new_name='key_responsibilities',
        ),
        migrations.AddField(
            model_name='job',
            name='skill_experience',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
