# Generated by Django 3.2 on 2022-10-12 10:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_auto_20221012_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about_company',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
