# Generated by Django 3.2 on 2022-09-16 09:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('front_image', models.ImageField(upload_to='Candidatefront')),
                ('candidate_content', tinymce.models.HTMLField()),
                ('sub_title', models.CharField(max_length=55)),
                ('sub_content', tinymce.models.HTMLField()),
                ('back_image', models.ImageField(upload_to='Candidatefront')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
