# Generated by Django 3.2 on 2022-10-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_candidatefront'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='blogdashboard',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactdashboard',
            options={'verbose_name_plural': 'Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='contactenquiry',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='indexdashboard',
            options={'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsconditions',
            options={'verbose_name_plural': 'Terms Conditions'},
        ),
        migrations.AlterModelOptions(
            name='testimonialdashboard',
            options={'verbose_name_plural': 'Testimonial'},
        ),
        migrations.AlterModelOptions(
            name='trainingdashboard',
            options={'verbose_name_plural': 'Training'},
        ),
    ]
