# Generated by Django 3.2 on 2022-08-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phonetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonetoken',
            old_name='used',
            new_name='isVerifed',
        ),
    ]
