# Generated by Django 3.2 on 2022-08-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_used_phonetoken_isverifed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
        migrations.DeleteModel(
            name='PhoneToken',
        ),
    ]
